spring.application.name=shortener
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortener
spring.datasource.username=root
spring.datasource.password=my-secret-pw
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret= 2e03463304e430595989ebbcc1636405633864a0ff820cc7fb6b17a49555af7e
jwt.expiration= 172800000

logging.level.org.springframework.security= DEBUG
logging.level.org.url.shoretener = DEBUG

